//
// Created by ShaudXiao on 2018/7/25.
//

#ifndef ANDROIDFFMPEGPLAYER_TEXTURE_FRAME_UPLOADER_H
#define ANDROIDFFMPEGPLAYER_TEXTURE_FRAME_UPLOADER_H

class TextureFrameUploader {
    
};

#endif //ANDROIDFFMPEGPLAYER_TEXTURE_FRAME_UPLOADER_H
