/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zx_androidffmpegplayer_video_player_KTVPlayer */

#ifndef _Included_com_zx_androidffmpegplayer_video_player_KTVPlayer
#define _Included_com_zx_androidffmpegplayer_video_player_KTVPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    onSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_onSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    onSurfaceDestroyed
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_onSurfaceDestroyed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    prepare
 * Signature: (Ljava/lang/String;[IIIZFFIILandroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_prepare
  (JNIEnv *, jobject, jstring, jintArray, jint, jint, jboolean, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_play
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    getBufferedProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_getBufferedProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    getPlayProgress
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_getPlayProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    seekToPosition
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_seekToPosition
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    seekCurrent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_seekCurrent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    beforeSeekCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_beforeSeekCurrent
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    afterSeekCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_afterSeekCurrent
  (JNIEnv *, jobject);

/*
 * Class:     com_zx_androidffmpegplayer_video_player_KTVPlayer
 * Method:    resetRenderSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_zx_androidffmpegplayer_video_player_KTVPlayer_resetRenderSize
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
